
// Generated by https://quicktype.io

export interface InfoPagina {
    titulo?:         string;
    facebook?:       string;
    instagram?:      string;
    email?:          string;
    nombre_corto?:   string;
    pagina_autor?:   string;
    tublr?:          string;
    equipo_trabajo?: any[];
}

